### ISSUE TITLE
Not able to access the output of libify.exporter(globals())

### ISSUE THREAD

**Issue by ethannakamura1211** [vagrantism/libify#1]
Currently it doesn't seem possible to access the json output of libify.exporter(globals()). The only way to do so is by copying it from the console. Is there a work-around?

**Comment by vagrantism** [comment]
@ethannakamura1211 Unless you are using Databricks Community, you would not need to copy the JSON from `libify.exporter(globals())`

- Are you using Databricks Community (https://community.cloud.databricks.com)?
- Did you try `libify.importer(globals(), '/path/to/ImportedNotebook')`? If yes, what was the output?

**Comment by businessglitch** [comment]
Hey man facing the issue, when I do an import
mod1 = libify.importer(globals(), config={"key": "IDoG5OWjB0Xxw_ECYzdVkBLyI_wAONLBS7bAL4MHrK4=", "file": "/tmp/tmpu4f3cyxr"})

it returns with a new path?! 
Notebook exited: {"key": "zZ3e1eAamCwbuqUZ1qmxaT1EaK7icsaLFK_wlGEB_rg=", "file": "/tmp/tmp0b1pl78g"}

**Comment by vagrantism** [comment]
Hi @businessglitch, are you using the Databricks Community Edition?

**Comment by businessglitch** [comment]
Hmm, i don't think so, using data bricks for a client directly from the Azure portal. In case if it doesn't work on that do you know any other libraries that do that same?

**Comment by vagrantism** [comment]
None that I'm aware of.
The code you are using is supposed to be used only for Databricks Community Cloud. For regular (paid) Databricks accounts, you can just do `mod1 = libify.importer(globals(), '/path/to/importee1')` where`/path/to/importee1` is the path to the notebook you are trying to import.
Look at the [Typical Usage](https://github.com/vagrantism/libify#typical-usage) part of the documentation for reference.

**Comment by NomanMasood** [comment]
Whatif someone needs to pass few arguments e.g. libify.importer(globals(), '/path/to/importee1 <need to pass two parameters/values/args>')? is it possible?  
 Alternate of this : dbutils.notebook.run("/path/to/importee1 ", 0, {"BATCH_ID": batch_id, "DB_Name" : db})

**Comment by vagrantism** [comment]
> Whatif someone needs to pass few arguments e.g. libify.importer(globals(), '/path/to/importee1 <need to pass two parameters/values/args>')? is it possible?
> Alternate of this : dbutils.notebook.run("/path/to/importee1 ", 0, {"BATCH_ID": batch_id, "DB_Name" : db})

I haven't come across a use case where parameters would need to be specified while importing a module. How are you planning on using these variables?
