### ISSUE TITLE
libified functions can't be pickled

### ISSUE THREAD

**Issue by JoshuaBWT** [vagrantism/libify#2]
Hey,

Thanks a lot for the lib, very useful! :) There is however one annoying issue with it at the moment.

Whenever we have the need to use a function that we import using libify within a dataframe foreach/foreachPartition we receive these errors:

`ModuleNotFoundError: No module named 'libified_'`
or
`Can't pickle <class 'libified_.BW'>: it's not found as libified_.BW`

My use-case is the following. I want to create a database connection for each partition to do some sort of batch export from a spark dataframe using https://github.com/SAP/PyHDB

If I create directly a pyhdb connection using `pyhdb.connect(...)` within my foreachPartition it works fine but if I am using a library that I imported with libify that would do a 
```
def get_connection():
  return pyhdb.connect(...)
```
it does not work with the errors mentioned above

**Comment by vagrantism** [comment]
Hi @JoshuaBWT,

Spark has issues pickling functions that use sparkcontext internally. Thanks for bringing this to my notice, I'll look into it.

In the meanwhile, would it be possible for you to post a minimal reproducible example?

**Comment by JoshuaBWT** [comment]
hey sorry for the delay inbetween responses, this was more specific than I thought.

It happens really when python classes are involved. Here's my example:

you have your library notebook called `lib`:
```
class Utils:
  
  def partition_processor(self, partition):
    print(list(partition))

from libify import exporter
exporter(globals())
```
and in your execution notebook:
```
import libify

utils = libify.importer(globals(), './lib')

df = spark.createDataFrame(list(range(1, 100)), 'INT')

def partition_function(partition):
  df_util = utils.Utils()
  return df_util.partition_processor(partition)

df.foreachPartition(partition_function)
```

maybe there is something wrong with my approach to spark's `foreachpartition` but the error seem very specific to libify

**Comment by vagrantism** [comment]
Hey @JoshuaBWT, it seems this issue can be solved easily by using `df_util = utils.Utils()` outside the function, i.e,  changing you code from 

```
def partition_function(partition):
  df_util = utils.Utils()
  return df_util.partition_processor(partition)
```

to 


```
df_util = utils.Utils()

def partition_function(partition):
  return df_util.partition_processor(partition)
```

The issue IMO is by calling `utils.Utils()` inside `foreachPartition`, it executes in a context which is different from the driver's main context (which is referenced by `globals()`), essentially causing the driver's `SparkContext` becoming unavailable to `utils`.

Here are the notebooks with a working example: [Importee](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4980917980199540/2432832133645008/8723993361985651/latest.html), [Importer](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4980917980199540/1316036888835426/8723993361985651/latest.html) 

And here's a screenshot showing the values getting printed (Not sure why it appears in STDERR, but unless you are really just trying to print stuff, it should be fine)
![image](https://user-images.githubusercontent.com/29144316/125117501-f7032380-e10b-11eb-9fbd-7b79692670e2.png)

If this fix does not solve your issue, feel free to reopen.
