### ISSUE TITLE
About importing function 

### ISSUE THREAD

**Issue by ayhandis** [vagrantism/libify#3]
**Code that I run:** 
!pip install libify
import libify
io = libify.importer(globals(), '/Users/ayhan.dis@ygroupcompanies.com/src/input_output/test_notebook')
function = io.cast_days()

**Error that I get:** 
AttributeError: module 'libified_' has no attribute 'cast_days'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-2320056099711594> in <module>
----> 1 function = io.cast_days()

AttributeError: module 'libified_' has no attribute 'cast_days

Code in the notebook: 
import pandas as pd
import libify

def cast_days(days):
    if not isinstance(days, pd.DatetimeIndex):
        return pd.DatetimeIndex(list(days))
    return days

libify.exporter(globals())

**Comment by vagrantism** [comment]
Hey @ayhandis, thanks for raising the issue. Can you try running `libify.exporter(globals())` in a different cell than the rest of your code and tell me if there's still an error?
