### ISSUE TITLE
Missing the dependencies setting in setup.py

### ISSUE THREAD

**Issue by kn1cht** [vagrantism/libify#7]
## Summary
`setup.py` in this package seems to have no `install_requires`. This causes error "ModuleNotFoundError: No module named 'cryptography'" when importing libify because pip doesn't know dependencies of the package.

## Version
v0.78

## Steps to Reproduce
```bash
$ pip install libify
Collecting libify
  Downloading libify-0.78-py3-none-any.whl (4.3 kB)
Installing collected packages: libify
Successfully installed libify-0.78

$ python -c "import libify"
Traceback (most recent call last):    
  File "<string>", line 1, in <module>
  File "/.../python3.8/site-packages/libify/__init__.py", line 3, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'
```

## Possible Solution
By writing dependencies in `setup.py`, pip should find information for the dependencies correctly.

```diff
--- a/setup.py
+++ b/setup.py
@@ -20,4 +20,7 @@ setup(name='libify',
         'Operating System :: OS Independent',
     ],
     python_requires='>=3.5',
+    install_requires=[
+      'cryptography>=37.0.2',
+    ],
     zip_safe=False)```

**Comment by vagrantism** [comment]
Great find @kn1cht! Would you be willing to open a PR for this?

**Comment by kn1cht** [comment]
I will (preparing PR)

**Comment by vagrantism** [comment]
Thanks for the PR @kn1cht, will review in some time. Just curious - are you planning on using this outside of Databricks? If yes, could you elaborate your use case?

**Comment by vagrantism** [comment]
Hey @kn1cht, I just cheked and it looks like the cryptography package is installed by default. Will re-open this issue if I get more such bugs.
