### ISSUE TITLE
Libify speed & debugging

### ISSUE THREAD

**Issue by fridrichmrtn** [vagrantism/libify#9]
Hi,

this is more of a question than a bug report.  I just implement the lib to organize code for my somewhat complex databricks project. However, I am experiencing significant drops in loading speeds when compared to standard `%run './utils'`, that is from seconds to minutes.

Is there something I could do to improve the loading speed?

Also, how do you debug such a code without reporting the actual error messages in the importing notebook?

Thanks.

Br,

MF

**Comment by vagrantism** [comment]
Re: improving loading speeds - a few things you could check:

1. What is happening in the imported notebook? The expectation is that the imported notebook should only have function / class definitions, and running the notebook itself would just create these classes/functions and not perform and operations that take time. The library uses something very similar to %run internally, so if there are time-taking operations inside the imported notebook, they are going to add to the latency.
2. Is the imported notebook very large? If that is the case, I'd recommend splitting it into smaller notebooks and importing only what's needed.
